package db_test

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"net/url"
	"os"
	"regexp"
	"slices"
	"testing"

	"github.com/calnode/calnode/internal/db"
)

// The PostgreSQL tests need a server, so they are opt-in: with
// CALNODE_TEST_POSTGRES_DSN unset they skip, and upstream CI and anyone running
// the SQLite build see no change. Point it at a database you are happy for a test
// to create and drop schemas in, e.g.
//
//	CALNODE_TEST_POSTGRES_DSN=postgres://postgres:pw@127.0.0.1:5432/calnode?sslmode=disable
const postgresDSNEnv = "CALNODE_TEST_POSTGRES_DSN"

// knownMigrationCount is the version a fully-migrated database must report. It is a
// sanity check on the embedded set, not a property of PostgreSQL, so it moves with
// every migration added — one named constant rather than the same literal in two
// assertions, so adding one is a single edit that cannot be half-done.
const knownMigrationCount = 68

// openTestPostgres returns a handle scoped to a schema of its own, created for
// this test and dropped when it finishes. A schema rather than a database because
// CREATE DATABASE cannot run inside a transaction and cannot be reached over the
// same connection, and a private schema is enough: goose_db_version and every
// table land inside it, so tests neither collide nor leave anything behind.
func openTestPostgres(t *testing.T) *db.DB {
	t.Helper()

	dsn := os.Getenv(postgresDSNEnv)
	if dsn == "" {
		t.Skipf("%s not set; skipping PostgreSQL tests", postgresDSNEnv)
	}

	admin, err := db.OpenDB(dsn)
	if err != nil {
		t.Fatalf("db.OpenDB(admin): %v", err)
	}
	defer admin.Close()

	// Random hex, not a test name: this is interpolated into DDL, and an
	// identifier we generated byte by byte cannot carry a quote or a keyword.
	buf := make([]byte, 8)
	if _, err := rand.Read(buf); err != nil {
		t.Fatalf("rand: %v", err)
	}
	schema := "calnode_test_" + hex.EncodeToString(buf)

	if _, err := admin.Exec(`CREATE SCHEMA ` + schema); err != nil {
		t.Fatalf("create schema %s: %v", schema, err)
	}

	handle, err := db.OpenDB(withSearchPath(t, dsn, schema))
	if err != nil {
		t.Fatalf("db.OpenDB(%s): %v", schema, err)
	}

	t.Cleanup(func() {
		handle.Close()

		cleanup, err := db.OpenDB(dsn)
		if err != nil {
			t.Errorf("reopen to drop schema %s: %v", schema, err)
			return
		}
		defer cleanup.Close()
		if _, err := cleanup.Exec(`DROP SCHEMA ` + schema + ` CASCADE`); err != nil {
			t.Errorf("drop schema %s: %v", schema, err)
		}
	})

	return handle
}

// withSearchPath adds search_path to the DSN. pgx forwards unrecognised URL
// parameters as server runtime parameters, so this pins every session on the
// handle to the test's schema without a per-connection hook.
func withSearchPath(t *testing.T, dsn, schema string) string {
	t.Helper()

	u, err := url.Parse(dsn)
	if err != nil {
		t.Fatalf("parse %s: %v", postgresDSNEnv, err)
	}
	q := u.Query()
	q.Set("search_path", schema)
	u.RawQuery = q.Encode()
	return u.String()
}

func TestPostgres_openDialectAndPool(t *testing.T) {
	handle := openTestPostgres(t)

	if got := handle.Dialect(); got != db.DialectPostgres {
		t.Errorf("dialect = %v; want %v", got, db.DialectPostgres)
	}
	// The SQLite single-connection rule must not have followed us here.
	if got := handle.Stats().MaxOpenConnections; got != 10 {
		t.Errorf("MaxOpenConnections = %d; want 10", got)
	}
	if err := handle.Ping(); err != nil {
		t.Fatalf("Ping: %v", err)
	}
}

func TestPostgres_migrateToTargetVersion(t *testing.T) {
	handle := openTestPostgres(t)
	ctx := context.Background()

	// Before migrating, the goose bookkeeping table is absent → not ready.
	if ready, _ := db.SchemaReady(ctx, handle.DB); ready {
		t.Error("SchemaReady = true before migrations ran; want false")
	}

	if err := handle.Migrate(); err != nil {
		t.Fatalf("Migrate: %v", err)
	}

	target, err := db.TargetVersion()
	if err != nil {
		t.Fatalf("TargetVersion: %v", err)
	}
	applied, err := db.AppliedVersion(ctx, handle.DB)
	if err != nil {
		t.Fatalf("AppliedVersion: %v", err)
	}
	if applied != target {
		t.Errorf("applied version = %d; want target %d", applied, target)
	}
	if target != knownMigrationCount {
		t.Errorf("target version = %d; want %d (sanity check against the known migration set)", target, knownMigrationCount)
	}

	ready, err := db.SchemaReady(ctx, handle.DB)
	if err != nil {
		t.Fatalf("SchemaReady after migrate: %v", err)
	}
	if !ready {
		t.Error("SchemaReady = false after migrations ran; want true")
	}
}

func TestPostgres_migrateIdempotent(t *testing.T) {
	handle := openTestPostgres(t)

	for range 2 {
		if err := handle.Migrate(); err != nil {
			t.Fatalf("Migrate: %v", err)
		}
	}
}

// TestPostgres_migrateViaPackageFunc covers the compatibility path: Migrate on a
// bare *sql.DB has to recover the dialect from the driver, and getting that wrong
// would run the SQLite migrations against Postgres.
func TestPostgres_migrateViaPackageFunc(t *testing.T) {
	handle := openTestPostgres(t)

	if err := db.Migrate(handle.DB); err != nil {
		t.Fatalf("db.Migrate: %v", err)
	}

	applied, err := db.AppliedVersion(context.Background(), handle.DB)
	if err != nil {
		t.Fatalf("AppliedVersion: %v", err)
	}
	if applied != knownMigrationCount {
		t.Errorf("applied version = %d; want %d", applied, knownMigrationCount)
	}
}

func TestPostgres_tablesExist(t *testing.T) {
	handle := openTestPostgres(t)

	if err := handle.Migrate(); err != nil {
		t.Fatalf("Migrate: %v", err)
	}

	tables := []string{
		"users", "api_keys", "teams", "team_members",
		"event_types", "event_type_questions",
		"availability_rules", "availability_overrides",
		"calendar_connections",
		"bookings", "booking_attendees", "booking_answers",
		"webhooks", "webhook_deliveries",
		"jobs",
		// Tables added by later migrations, so this also proves the whole set ran.
		"server_settings", "crypto_keystore", "event_type_hosts", "booking_hosts",
		"idempotency_keys", "oauth_access_tokens", "zoom_connections",
		"magic_link_tokens", "recordings", "meeting_consents", "transcripts",
		"notes", "connection_calendars",
	}

	for _, table := range tables {
		var name string
		err := handle.QueryRow(
			`SELECT table_name FROM information_schema.tables
			 WHERE table_schema = current_schema() AND table_name = ?`, table,
		).Scan(&name)
		if err != nil {
			t.Errorf("table %q not found after migration: %v", table, err)
		}
	}
}

// TestPostgres_doubleBookingIndex checks the partial unique index carried over as
// a partial index. Without the WHERE clause it would block a re-book of a
// cancelled slot, which is the behaviour the SQLite index deliberately avoids.
func TestPostgres_doubleBookingIndex(t *testing.T) {
	handle := openTestPostgres(t)

	if err := handle.Migrate(); err != nil {
		t.Fatalf("Migrate: %v", err)
	}

	var indexdef string
	err := handle.QueryRow(
		`SELECT indexdef FROM pg_indexes
		 WHERE schemaname = current_schema() AND indexname = 'idx_bookings_no_double'`,
	).Scan(&indexdef)
	if err != nil {
		t.Fatalf("double-booking guard index not found: %v", err)
	}

	for _, want := range []string{"UNIQUE", "host_id", "start_at", "WHERE"} {
		if !regexp.MustCompile(want).MatchString(indexdef) {
			t.Errorf("index definition %q is missing %q", indexdef, want)
		}
	}
}

// TestPostgres_flagColumnsStayIntegers is the load-bearing type check: the 0/1
// flag columns are read into Go ints all over the codebase, so a translation that
// turned them into BOOLEAN would break every one of those scans.
func TestPostgres_flagColumnsStayIntegers(t *testing.T) {
	handle := openTestPostgres(t)

	if err := handle.Migrate(); err != nil {
		t.Fatalf("Migrate: %v", err)
	}

	flags := []struct{ table, column string }{
		{"users", "is_admin"},
		{"users", "is_owner"},
		{"users", "email_login"},
		{"users", "notify_confirmation"},
		{"event_types", "is_active"},
		{"event_types", "is_public"},
		{"event_types", "show_taken_slots"},
		{"event_type_questions", "required"},
		{"availability_overrides", "is_available"},
		{"calendar_connections", "check_conflicts"},
		{"calendar_connections", "is_destination"},
		{"connection_calendars", "check_conflicts"},
		{"booking_attendees", "is_organizer"},
		{"booking_hosts", "is_primary"},
		{"booking_hosts", "needs_sync"},
		{"server_settings", "smtp_tls"},
		{"server_settings", "smtp_starttls"},
		{"server_settings", "llm_enabled"},
		{"server_settings", "recordings_enabled"},
		{"server_settings", "notetaker_enabled"},
	}

	for _, f := range flags {
		var dataType string
		err := handle.QueryRow(
			`SELECT data_type FROM information_schema.columns
			 WHERE table_schema = current_schema() AND table_name = ? AND column_name = ?`,
			f.table, f.column,
		).Scan(&dataType)
		if err != nil {
			t.Errorf("%s.%s: %v", f.table, f.column, err)
			continue
		}
		if dataType != "smallint" && dataType != "integer" {
			t.Errorf("%s.%s is %q; want an integer type (763 call sites scan these into Go ints)",
				f.table, f.column, dataType)
		}
	}

	// Prove the scan, not just the catalogue: server_settings is seeded by 00011.
	var smtpTLS, smtpStartTLS int
	if err := handle.QueryRow(
		`SELECT smtp_tls, smtp_starttls FROM server_settings WHERE id = ?`, 1,
	).Scan(&smtpTLS, &smtpStartTLS); err != nil {
		t.Fatalf("scan flag columns into int: %v", err)
	}
	if smtpTLS != 0 || smtpStartTLS != 1 {
		t.Errorf("seeded flags = (%d, %d); want (0, 1)", smtpTLS, smtpStartTLS)
	}
}

// TestPostgres_timestampDefaultsMatchSQLite pins the format of the defaulted
// timestamp columns. They stay TEXT holding the same strings SQLite writes,
// because every time column in this schema is compared and sorted as a string.
func TestPostgres_timestampDefaultsMatchSQLite(t *testing.T) {
	handle := openTestPostgres(t)

	if err := handle.Migrate(); err != nil {
		t.Fatalf("Migrate: %v", err)
	}

	// users.created_at defaults to SQLite's strftime('%Y-%m-%dT%H:%M:%fZ','now').
	if _, err := handle.Exec(
		`INSERT INTO users (id, email, name) VALUES (?, ?, ?)`,
		"u1", "a@example.com", "A"); err != nil {
		t.Fatalf("insert user: %v", err)
	}

	var createdAt string
	if err := handle.QueryRow(`SELECT created_at FROM users WHERE id = ?`, "u1").Scan(&createdAt); err != nil {
		t.Fatalf("read created_at: %v", err)
	}
	const isoMillis = `^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$`
	if !regexp.MustCompile(isoMillis).MatchString(createdAt) {
		t.Errorf("users.created_at = %q; want SQLite's %s form", createdAt, isoMillis)
	}

	// server_settings.updated_at defaults to SQLite's datetime('now').
	var updatedAt string
	if err := handle.QueryRow(`SELECT updated_at FROM server_settings WHERE id = ?`, 1).Scan(&updatedAt); err != nil {
		t.Fatalf("read updated_at: %v", err)
	}
	const secondsUTC = `^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$`
	if !regexp.MustCompile(secondsUTC).MatchString(updatedAt) {
		t.Errorf("server_settings.updated_at = %q; want SQLite's %s form", updatedAt, secondsUTC)
	}
}

// TestPostgres_identityPrimaryKey covers the one column that relied on SQLite's
// rowid: keyvault.go inserts a keystore entry without an id.
func TestPostgres_identityPrimaryKey(t *testing.T) {
	handle := openTestPostgres(t)

	if err := handle.Migrate(); err != nil {
		t.Fatalf("Migrate: %v", err)
	}

	if _, err := handle.Exec(`
		INSERT INTO crypto_keystore
		  (label, wrapped_dek, kdf, kdf_salt, kdf_params, dek_version, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, 1, ?, ?)`,
		"primary", []byte("wrapped"), "argon2id", []byte("salt"), `{"m":65536,"t":3,"p":2}`,
		"2026-01-01T00:00:00.000Z", "2026-01-01T00:00:00.000Z"); err != nil {
		t.Fatalf("insert keystore entry without an id: %v", err)
	}

	var id int64
	var wrapped []byte
	if err := handle.QueryRow(
		`SELECT id, wrapped_dek FROM crypto_keystore WHERE label = ?`, "primary",
	).Scan(&id, &wrapped); err != nil {
		t.Fatalf("read keystore entry: %v", err)
	}
	if id == 0 {
		t.Error("id was not assigned; the identity column is missing")
	}
	if string(wrapped) != "wrapped" {
		t.Errorf("wrapped_dek = %q; want %q (BYTEA round trip)", wrapped, "wrapped")
	}
}

// TestPostgres_wrapperRebinds is the end-to-end proof that the wrapper is what
// makes ?-placeholder SQL work here: the same statement through the bare handle
// must fail.
func TestPostgres_wrapperRebinds(t *testing.T) {
	handle := openTestPostgres(t)
	ctx := context.Background()

	if err := handle.Migrate(); err != nil {
		t.Fatalf("Migrate: %v", err)
	}

	if _, err := handle.ExecContext(ctx,
		`INSERT INTO users (id, email, name) VALUES (?, ?, ?)`,
		"u1", "a@example.com", "A"); err != nil {
		t.Fatalf("ExecContext through the wrapper: %v", err)
	}

	if _, err := handle.DB.ExecContext(ctx,
		`INSERT INTO users (id, email, name) VALUES (?, ?, ?)`,
		"u2", "b@example.com", "B"); err == nil {
		t.Error("? placeholders succeeded on the bare *sql.DB; the rebinding test proves nothing")
	}

	var name string
	if err := handle.QueryRowContext(ctx,
		`SELECT name FROM users WHERE email = ? AND is_admin = ?`, "a@example.com", 0).Scan(&name); err != nil {
		t.Fatalf("QueryRowContext: %v", err)
	}
	if name != "A" {
		t.Errorf("name = %q; want %q", name, "A")
	}

	rows, err := handle.QueryContext(ctx, `SELECT id FROM users WHERE email = ?`, "a@example.com")
	if err != nil {
		t.Fatalf("QueryContext: %v", err)
	}
	count := 0
	for rows.Next() {
		count++
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows.Err: %v", err)
	}
	rows.Close()
	if count != 1 {
		t.Errorf("rows returned = %d; want 1", count)
	}

	tx, err := handle.BeginTx(ctx, nil)
	if err != nil {
		t.Fatalf("BeginTx: %v", err)
	}
	if _, err := tx.ExecContext(ctx, `UPDATE users SET name = ? WHERE id = ?`, "B", "u1"); err != nil {
		tx.Rollback()
		t.Fatalf("tx.ExecContext: %v", err)
	}
	if err := tx.QueryRowContext(ctx, `SELECT name FROM users WHERE id = ?`, "u1").Scan(&name); err != nil {
		tx.Rollback()
		t.Fatalf("tx.QueryRowContext: %v", err)
	}
	if err := tx.Commit(); err != nil {
		t.Fatalf("tx.Commit: %v", err)
	}
	if name != "B" {
		t.Errorf("name after tx update = %q; want %q", name, "B")
	}

	stmt, err := handle.PrepareContext(ctx, `SELECT COUNT(*) FROM users WHERE email = ?`)
	if err != nil {
		t.Fatalf("PrepareContext: %v", err)
	}
	defer stmt.Close()
	var n int
	if err := stmt.QueryRowContext(ctx, "a@example.com").Scan(&n); err != nil {
		t.Fatalf("stmt.QueryRowContext: %v", err)
	}
	if n != 1 {
		t.Errorf("count = %d; want 1", n)
	}
}

// TestPostgres_partialUniqueIndexEnforced exercises the double-booking guard
// itself rather than its definition: the index is the only thing standing between
// two concurrent bookings and a double-booked host now that Postgres has a
// connection pool (see openPostgres).
func TestPostgres_partialUniqueIndexEnforced(t *testing.T) {
	handle := openTestPostgres(t)
	ctx := context.Background()

	if err := handle.Migrate(); err != nil {
		t.Fatalf("Migrate: %v", err)
	}

	seed := []struct {
		query string
		args  []any
	}{
		{`INSERT INTO users (id, email, name) VALUES (?, ?, ?)`, []any{"h1", "h@example.com", "Host"}},
		{`INSERT INTO event_types (id, user_id, slug, name, duration_minutes) VALUES (?, ?, ?, ?, ?)`,
			[]any{"e1", "h1", "intro", "Intro", 30}},
		{`INSERT INTO bookings (id, event_type_id, host_id, start_at, end_at) VALUES (?, ?, ?, ?, ?)`,
			[]any{"b1", "e1", "h1", "2026-01-01T10:00:00.000Z", "2026-01-01T10:30:00.000Z"}},
	}
	for _, s := range seed {
		if _, err := handle.ExecContext(ctx, s.query, s.args...); err != nil {
			t.Fatalf("seed %q: %v", s.query, err)
		}
	}

	// Same host, same start: refused.
	if _, err := handle.ExecContext(ctx,
		`INSERT INTO bookings (id, event_type_id, host_id, start_at, end_at) VALUES (?, ?, ?, ?, ?)`,
		"b2", "e1", "h1", "2026-01-01T10:00:00.000Z", "2026-01-01T10:30:00.000Z"); err == nil {
		t.Error("second booking at the same start time was accepted; the guard index is not enforcing")
	}

	// Cancelling the first frees the slot — the point of the WHERE clause.
	if _, err := handle.ExecContext(ctx,
		`UPDATE bookings SET status = 'cancelled' WHERE id = ?`, "b1"); err != nil {
		t.Fatalf("cancel booking: %v", err)
	}
	if _, err := handle.ExecContext(ctx,
		`INSERT INTO bookings (id, event_type_id, host_id, start_at, end_at) VALUES (?, ?, ?, ?, ?)`,
		"b3", "e1", "h1", "2026-01-01T10:00:00.000Z", "2026-01-01T10:30:00.000Z"); err != nil {
		t.Errorf("re-booking a cancelled slot was refused: %v", err)
	}
}

// TestPostgres_schemaMatchesSQLite migrates both engines and compares the result,
// table by table and column by column. It is the check the translation actually
// needs: every other test here says a specific thing survived, and this one says
// nothing was quietly dropped, renamed or added along the way.
//
// Names only, not types: TEXT versus text and SMALLINT versus integer are the
// translation working as intended, and the types that do matter are pinned by
// TestPostgres_flagColumnsStayIntegers.
func TestPostgres_schemaMatchesSQLite(t *testing.T) {
	postgres := openTestPostgres(t)
	if err := postgres.Migrate(); err != nil {
		t.Fatalf("Migrate(postgres): %v", err)
	}

	sqlite, err := db.OpenDB("sqlite://:memory:")
	if err != nil {
		t.Fatalf("db.OpenDB(sqlite): %v", err)
	}
	defer sqlite.Close()
	if err := sqlite.Migrate(); err != nil {
		t.Fatalf("Migrate(sqlite): %v", err)
	}

	sqliteSchema := sqliteColumns(t, sqlite)
	postgresSchema := postgresColumns(t, postgres)

	// Guard against a vacuous pass: an empty map on either side would satisfy
	// every comparison below.
	if len(sqliteSchema) < 30 {
		t.Fatalf("only %d tables found on SQLite; the comparison would prove nothing", len(sqliteSchema))
	}

	for table, want := range sqliteSchema {
		got, ok := postgresSchema[table]
		if !ok {
			t.Errorf("table %q exists on SQLite and not on Postgres", table)
			continue
		}
		if !slices.Equal(want, got) {
			t.Errorf("table %q columns differ\n sqlite: %v\n  pgsql: %v", table, want, got)
		}
	}
	for table := range postgresSchema {
		if _, ok := sqliteSchema[table]; !ok {
			t.Errorf("table %q exists on Postgres and not on SQLite", table)
		}
	}
}

// sqliteColumns maps table name to sorted column names, skipping SQLite's own
// bookkeeping tables (sqlite_sequence appears because goose's version table uses
// AUTOINCREMENT).
func sqliteColumns(t *testing.T, handle *db.DB) map[string][]string {
	t.Helper()

	rows, err := handle.Query(
		`SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name`)
	if err != nil {
		t.Fatalf("list sqlite tables: %v", err)
	}
	tables := scanStrings(t, rows)

	schema := make(map[string][]string, len(tables))
	for _, table := range tables {
		// PRAGMA table_info takes no placeholder; the name comes from
		// sqlite_master, not from input.
		rows, err := handle.Query(`SELECT name FROM pragma_table_info('` + table + `')`)
		if err != nil {
			t.Fatalf("columns of %q: %v", table, err)
		}
		cols := scanStrings(t, rows)
		slices.Sort(cols)
		schema[table] = cols
	}
	return schema
}

// postgresColumns maps table name to sorted column names for the test schema.
func postgresColumns(t *testing.T, handle *db.DB) map[string][]string {
	t.Helper()

	rows, err := handle.Query(
		`SELECT table_name FROM information_schema.tables
		 WHERE table_schema = current_schema() AND table_type = 'BASE TABLE'
		 ORDER BY table_name`)
	if err != nil {
		t.Fatalf("list postgres tables: %v", err)
	}
	tables := scanStrings(t, rows)

	schema := make(map[string][]string, len(tables))
	for _, table := range tables {
		rows, err := handle.Query(
			`SELECT column_name FROM information_schema.columns
			 WHERE table_schema = current_schema() AND table_name = ?`, table)
		if err != nil {
			t.Fatalf("columns of %q: %v", table, err)
		}
		cols := scanStrings(t, rows)
		slices.Sort(cols)
		schema[table] = cols
	}
	return schema
}

func scanStrings(t *testing.T, rows *db.Rows) []string {
	t.Helper()
	defer rows.Close()

	var out []string
	for rows.Next() {
		var s string
		if err := rows.Scan(&s); err != nil {
			t.Fatalf("scan: %v", err)
		}
		out = append(out, s)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows.Err: %v", err)
	}
	return out
}
